Repository wecode-bootcamp-korea/29-1st-KIKEA-frontend, pull requests merged in 2022-02, with the labels that each got.

#3 [29기] 문지원 : 공용 컴포넌트 추가
  package-lock.json
  package.json
  public/data/data.json
  public/images/kikeaLogo.png
  public/index.html
  src/Router.js
  src/components/Menu/LoginBar/LoginBar.js
  src/components/Menu/LoginBar/LoginBar.scss
  src/components/Menu/Menu/Menu.js
  src/components/Menu/Menu/Menu.scss
  src/components/Menu/MenuChild/MenuChild.js
  src/components/Menu/MenuChild/MenuChild.scss
  src/components/Nav.js
  src/components/Nav.scss
  src/components/Nav/Nav.js
  src/components/NavBar/NavBar.js
  src/components/NavBar/NaviBar.scss
  src/components/NavBar/SearchBox/SearchBox.js
  src/components/NavBar/SearchBox/SearchBox.scss
  src/components/NavBar/SearchFilter/SearchFilter.js
  src/components/NavBar/SearchFilter/SearchFilter.scss
  src/components/TopBar/TopBar.js
  src/components/TopBar/TopBar.scss
  src/pages/Main/Main.js
Labels: Status: 수정중

#7 [29기 신수녕] main 페이지 백엔드 통신하는 것으로 코드 수정
  src/pages/Main/Main.js
  src/pages/Main/MainProduct/MainProduct.js
  src/pages/Main/MainProduct/MainProduct.scss
  src/pages/Main/MainProduct/ProductFilter/ProductFilter.js
  src/pages/Main/MainProduct/ProductItem/ProductItem.js
  src/pages/Main/RecommentItem/RecommendItem.js
  src/pages/Main/RecommentItem/RecommendItem.scss
Labels: Status: 리뷰 요청

#6 [29기 신수녕] 로그인 페이지 UI
  public/images/logo.jpg
  src/Router.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/LoginAside/LoginAside.js
  src/pages/Login/LoginAside/LoginAside.scss
  src/pages/Login/LoginMain/LoginMain.js
  src/pages/Login/LoginMain/LoginMain.scss
Labels: Status: 리뷰 요청

#5 [29기] 신수녕 회원가입 페이지 추가
  public/images/images.png
  src/Router.js
  src/pages/Member/Member.js
  src/pages/Member/Member.scss
  src/pages/Member/MemberSide/MemberSide.js
  src/pages/Member/MemberSide/MemberSide.scss
  src/pages/Member/SignUpForm/SignUpForm.js
  src/pages/Member/SignUpForm/SignUpForm.scss
Labels: Status: 리뷰 요청

#2 [29기 박혜린] 상세페이지 UI 및 목데이터
  public/data/detailMainData.json
  src/Router.js
  src/pages/Detail/DetailAside/DetailAside.js
  src/pages/Detail/DetailAside/DetailAside.scss
  src/pages/Detail/DetailC.js
  src/pages/Detail/DetailC.scss
  src/pages/Detail/DetailDescSide/DetailDescSide.js
  src/pages/Detail/DetailDescSide/DetailDescSide.scss
  src/pages/Detail/DetailMain/DetailDesc.js
  src/pages/Detail/DetailMain/DetailDesc.scss
  src/pages/Detail/DetailMain/DetailMain.js
  src/pages/Detail/DetailMain/DetailMain.scss
  src/pages/Detail/DetailMain/DetailRel/DetailRec.js
  src/pages/Detail/DetailMain/DetailRel/DetailRec.scss
  src/pages/Detail/DetailMain/DetailRel/DetailRecProd.js
  src/pages/Detail/DetailMain/DetailRel/DetailRecProd.scss
  src/pages/Detail/DetailMain/ProductImg.js
  src/pages/Detail/DetailMain/ProductImg.scss
  src/pages/Detail/DetailNav.js
  src/pages/Detail/DetailNav.scss
  src/pages/Detail/DetailReviewSide/DetailReviewSide.js
  src/pages/Detail/DetailReviewSide/DetailReviewSide.scss
  src/pages/Detail/DetailSide/DetailSide.js
  src/pages/Detail/DetailSide/DetailSide.scss
Labels: Status: 리뷰 요청, Status: Conflict 해결 요청

#4 [29기] 문지원 : ProductType 페이지
  src/Router.js
  src/pages/ProductType/ProductCategory/ProductCategory.js
  src/pages/ProductType/ProductCategory/ProductCategory.scss
  src/pages/ProductType/ProductFilter/ProductCard/ProductCard.js
  src/pages/ProductType/ProductFilter/ProductCard/ProductCard.scss
  src/pages/ProductType/ProductFilter/ProductFilter.js
  src/pages/ProductType/ProductFilter/ProductFilter.scss
  src/pages/ProductType/ProductSuggestion/ProductSuggestion.js
  src/pages/ProductType/ProductSuggestion/ProductSuggestion.scss
  src/pages/ProductType/ProductTypeMain.js
  src/pages/ProductType/ProductTypeMain.scss
Labels: Status: 리뷰 요청

#9 [29기 신수녕] 메인페이지 이미지 슬라이드 추가, nav바 추가
  src/Router.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainProduct/MainProduct.scss
  src/pages/Main/RecommentItem/RecommendItem.js
  src/pages/Main/RecommentItem/RecommendItem.scss
Labels: Status: 리뷰 요청

#10 [29기 박혜린] Detail Page - 추천제품 캐러셀 구현, 사이드바 toggle 수정
  public/data/detailMainData.json
  src/pages/Detail/DetailAside/DetailAside.scss
  src/pages/Detail/DetailC.js
  src/pages/Detail/DetailC.scss
  src/pages/Detail/DetailMain/DetailRel/DetailRec.js
  src/pages/Detail/DetailMain/DetailRel/DetailRec.scss
  src/pages/Detail/DetailMain/DetailRel/DetailRecProd.scss
  src/pages/Detail/DetailSide/DetailSide.js
  src/pages/Detail/DetailSide/DetailSide.scss
Labels: Status: 리뷰 요청

#11 [29기 신수녕] 푸터 컴포넌트 추가
  package-lock.json
  package.json
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#13 [29기 문지원] ProductType페이지 PR
  src/Router.js
  src/pages/ProductType/ProductCategory/ProductCategory.js
  src/pages/ProductType/ProductFilter/ProductCard/ProductCard.js
  src/pages/ProductType/ProductFilter/ProductFilter.js
  src/pages/ProductType/ProductFilter/ProductFilter.scss
  src/pages/ProductType/ProductSuggestion/ProductSuggestion.scss
  src/pages/ProductType/ProductTypeMain.js
Labels: Status: 리뷰 요청

#15 [29기 신수녕] 백엔드 통신 후 에러 처리
  src/pages/Member/SignUpForm/SignUpForm.js
Labels: Status: 리뷰 요청

#8 [29기 박혜린] cart page UI
  package-lock.json
  package.json
  public/data/cartData.json
  src/Router.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartMain/CartBox/CartBox.js
  src/pages/Cart/CartMain/CartBox/CartBox.scss
  src/pages/Cart/CartMain/CartMain.js
  src/pages/Cart/CartMain/CartMain.scss
  src/pages/Cart/CartMain/CartRecProd/CartRecBox.js
  src/pages/Cart/CartMain/CartRecProd/CartRecBox.scss
  src/pages/Cart/CartMain/CartRecProd/CartRecProd.js
  src/pages/Cart/CartMain/CartRecProd/CartRecProd.scss
  src/pages/Cart/CartSide/CartSide.js
  src/pages/Cart/CartSide/CartSide.scss
Labels: Status: 수정중

#16 [29기 신수녕] 전반적인 css 수정, 백엔드 통신
  src/Router.js
  src/components/Menu/LoginBar/LoginBar.js
  src/components/Menu/LoginBar/LoginBar.scss
  src/components/Menu/Menu/List/List.js
  src/components/Menu/Menu/List/List.scss
  src/components/Menu/Menu/Menu.scss
  src/components/NavBar/NavIcons/NavIcons.js
  src/components/NavBar/NavIcons/NavIcons.scss
  src/components/NavBar/NaviBar.scss
  src/components/NavBar/SearchBox/SearchBox.scss
  src/components/NavBar/SearchFilter/SearchFilter.scss
  src/components/TopBar/TopBar.scss
  src/pages/Login/LoginMain/LoginMain.js
  src/pages/Main/MainProduct/MainProduct.js
  src/pages/Main/MainProduct/MainProduct.scss
  src/pages/Main/MainProduct/ProductFilter/ProductFilter.js
  src/pages/Main/MainProduct/ProductItem/ProductItem.js
  src/pages/Main/Promotion/Promotion.js
  src/pages/Main/Promotion/Promotion.scss
  src/pages/Main/Promotion/PromotionCard/PromotionCard.js
  src/pages/Main/Promotion/PromotionCard/PromotionCard.scss
  src/pages/Main/RecommentItem/RecommendItem.js
  src/pages/Main/RecommentItem/RecommendItem.scss
  src/pages/Member/MemberSide/MemberSide.js
Labels: Status: 리뷰 요청

#18 [29기 박혜린] 리뷰 반영 수정
  public/data/cartData.json
  src/Router.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartMain/CartBox/CartBox.js
  src/pages/Cart/CartMain/CartBox/CartBox.scss
  src/pages/Cart/CartMain/CartMain.js
  src/pages/Cart/CartMain/CartMain.scss
  src/pages/Cart/CartMain/CartRecProd/CartRecBox.js
  src/pages/Cart/CartMain/CartRecProd/CartRecBox.scss
  src/pages/Cart/CartMain/CartRecProd/CartRecProd.js
  src/pages/Cart/CartMain/CartRecProd/CartRecProd.scss
  src/pages/Cart/CartSide/CartSide.js
  src/pages/Cart/CartSide/CartSide.scss
  src/pages/Detail/DetailMain/DetailRel/CartRecBox.js
  src/pages/Detail/DetailMain/DetailRel/CartRecBox.scss
Labels: Status: 리뷰 요청

#19 [29기 박혜린] Detail PR
  src/Router.js
  src/pages/Cart/Cart.scss
  src/pages/Detail/DetailAside/DetailAside.js
  src/pages/Detail/DetailAside/DetailAside.scss
  src/pages/Detail/DetailC.js
  src/pages/Detail/DetailC.scss
  src/pages/Detail/DetailDescSide/DetailDescSide.js
  src/pages/Detail/DetailDescSide/DetailDescSide.scss
  src/pages/Detail/DetailMain/DetailDesc.js
  src/pages/Detail/DetailMain/DetailMain.js
  src/pages/Detail/DetailMain/DetailMain.scss
  src/pages/Detail/DetailMain/DetailRel/DetailRec.js
  src/pages/Detail/DetailMain/DetailRel/DetailRec.scss
  src/pages/Detail/DetailMain/DetailRel/DetailRecProd.js
  src/pages/Detail/DetailMain/DetailRel/DetailRecProd.scss
  src/pages/Detail/DetailMain/ProductImg.js
  src/pages/Detail/DetailNav.scss
  src/pages/Detail/DetailSide/DetailColor.js
  src/pages/Detail/DetailSide/DetailColor.scss
  src/pages/Detail/DetailSide/DetailSide.js
  src/pages/Detail/DetailSide/DetailSide.scss
  src/pages/Detail/DetailSide/DetailSize.js
  src/pages/Detail/DetailSide/DetailSize.scss
  src/pages/Login/LoginMain/LoginMain.js
Labels: Status: 리뷰 요청

#20 [29기 신수녕] nav, main 링크 수정
  public/images/blackStar.png
  public/images/star.png
  src/Router.js
  src/components/Footer/Footer.scss
  src/components/Menu/Menu/List/List.js
  src/components/Menu/Menu/List/List.scss
  src/components/NavBar/NavBar.js
  src/components/NavBar/SearchFilter/SearchCard/SearchCard.js
  src/components/NavBar/SearchFilter/SearchFilter.js
  src/config.js
  src/pages/Login/LoginMain/LoginMain.js
  src/pages/Main/MainProduct/MainProduct.js
  src/pages/Main/MainProduct/ProductFilter/ProductFilter.js
  src/pages/Main/MainProduct/ProductItem/ProductItem.js
  src/pages/Main/MainProduct/ProductItem/ProductItem.scss
  src/pages/Main/RecommentItem/RecommendItem.js
  src/pages/Main/RecommentItem/RecommendItem.scss
  src/pages/Member/SignUpForm/SignUpForm.js
Labels: Status: 리뷰 요청

#21 [29기 신수녕] 결제 페이지 추가
  README.md
  src/Router.js
  src/pages/Order/Order.js
  src/pages/Order/Order.scss
  src/pages/Order/OrderInfo/OrderInfo.js
  src/pages/Order/OrderInfo/OrderInfo.scss
  src/pages/Order/OrderMain/OrderMain.js
  src/pages/Order/OrderMain/OrderMain.scss
  src/pages/Order/OrderTop/OrderTop.js
  src/pages/Order/OrderTop/OrderTop.scss
Labels: Status: 리뷰 요청

#22 [29기 문지원] ProductType 페이지 PR
  public/data/data.json
  src/Router.js
  src/components/NavBar/NavBar.js
  src/components/NavBar/SearchFilter/SearchCard/SearchCard.js
  src/config.js
  src/pages/ProductType/Mock/SuggestionData.js
  src/pages/ProductType/Mock/TipsData.js
  src/pages/ProductType/ProductCategory/ProductCategory.js
  src/pages/ProductType/ProductCategory/ProductCategory.scss
  src/pages/ProductType/ProductFilter/ProductCard/ProductCard.js
  src/pages/ProductType/ProductFilter/ProductCard/ProductCard.scss
  src/pages/ProductType/ProductFilter/ProductFilter.js
  src/pages/ProductType/ProductFilter/ProductFilter.scss
  src/pages/ProductType/ProductSuggestion/ProductSuggestion.js
  src/pages/ProductType/ProductSuggestion/ProductSuggestion.scss
  src/pages/ProductType/ProductTips/ProductTips.js
  src/pages/ProductType/ProductTips/ProductTips.scss
  src/pages/ProductType/ProductTypeMain.js
Labels: Status: 리뷰 요청

#23 [29기 박혜린] 장바구니 페이지 (제품 수량 변경 기능 추가)
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartMain/CartBox/CartBox.js
  src/pages/Cart/CartMain/CartBox/CartBox.scss
  src/pages/Cart/CartMain/CartMain.js
  src/pages/Cart/CartMain/CartMain.scss
  src/pages/Cart/CartMain/CartRecProd/CartRecBox.js
  src/pages/Cart/CartMain/CartRecProd/CartRecBox.scss
  src/pages/Cart/CartMain/CartRecProd/CartRecProd.js
  src/pages/Cart/CartSide/CartSide.js
  src/pages/Login/LoginMain/LoginMain.js
Labels: Status: 리뷰 요청

#24 [29기 박혜린] - 최종 수정
  src/pages/Cart/Cart.js
  src/pages/Cart/CartMain/CartBox/CartBox.js
  src/pages/Cart/CartMain/CartMain.js
  src/pages/Cart/CartSide/CartSide.js
Labels: Status: 리뷰 요청

#25 [29기 신수녕] 최종 종합본입니다.
  src/Router.js
  src/components/Menu/Menu/List/List.js
  src/components/Menu/Menu/Menu.js
  src/components/Nav.js
  src/config.js
  src/pages/Detail/DetailC.js
  src/pages/Login/LoginMain/LoginMain.js
  src/pages/Main/MainProduct/ProductItem/ProductItem.js
  src/pages/Order/OrderInfo/OrderInfo.js
  src/pages/Order/OrderInfo/OrderInfo.scss
  src/pages/ProductType/ProductTypeMain.js
Labels: Status: 리뷰 요청
